import { Agent, ActivityEntry, ScheduledTask, AlwaysRunningProcess } from './types';

export const agents: Agent[] = [
  {
    id: 'codex',
    name: 'Codex',
    role: 'Chief of Staff',
    description: 'Coordinates, delegates, keeps the ship tight. The first point of contact between boss and machine.',
    skills: ['Orchestration', 'Clarity', 'Delegation'],
    color: '#6366f1',
    avatar: '🤖',
    status: 'active',
    currentTask: 'Coordinating team...',
    tier: 'chief',
  },
  {
    id: 'claude',
    name: 'Claude',
    role: 'Infrastructure Engineer',
    description: 'Infrastructure and automation specialist. Handles coding, deployments, and system architecture.',
    skills: ['Coding', 'Infrastructure', 'Automation'],
    color: '#f97316',
    avatar: '🔧',
    status: 'active',
    currentTask: 'Working...',
    tier: 'operations',
  },
  {
    id: 'gemini',
    name: 'Gemini',
    role: 'Foreman / QA Manager',
    description: 'Checks the work, signs off or sends it back. No-nonsense quality control.',
    skills: ['Quality Assurance', 'Monitoring', 'Demo Recording'],
    color: '#ec4899',
    avatar: '🔍',
    status: 'active',
    currentTask: 'Working...',
    tier: 'operations',
  },
  {
    id: 'scout',
    name: 'Scout',
    role: 'Trend Analyst',
    description: 'Finds leads, tracks signals, scouts opportunities in the market.',
    skills: ['Speed', 'Radar', 'Intuition'],
    color: '#84cc16',
    avatar: '🔭',
    status: 'idle',
    currentTask: null,
    tier: 'signal',
  },
  {
    id: 'quill',
    name: 'Quill',
    role: 'Content Writer',
    description: 'Writes copy, designs content strategies, crafts narratives.',
    skills: ['Voice', 'Quality', 'Design'],
    color: '#eab308',
    avatar: '✍️',
    status: 'active',
    currentTask: 'Writing newsletter...',
    tier: 'signal',
  },
  {
    id: 'pixel',
    name: 'Pixel',
    role: 'Thumbnail Designer',
    description: 'Designs thumbnails, crafts visuals, creates brand assets.',
    skills: ['Visual', 'Attention', 'Style'],
    color: '#f43f5e',
    avatar: '🎨',
    status: 'idle',
    currentTask: null,
    tier: 'output',
  },
  {
    id: 'echo',
    name: 'Echo',
    role: 'Social Media Manager',
    description: 'Posts, engages, grows the audience across all platforms.',
    skills: ['Viral', 'Speed', 'Reach'],
    color: '#06b6d4',
    avatar: '📢',
    status: 'active',
    currentTask: 'Scheduling tweets',
    tier: 'output',
  },
];

export const mockActivities: ActivityEntry[] = [
  { id: '1', agentId: 'scout', agentName: 'Scout', type: 'competitor alert', message: 'Competitor alert: new Claude Code tutor...', timestamp: new Date(Date.now() - 1 * 60000), color: '#84cc16' },
  { id: '2', agentId: 'codex', agentName: 'Codex', type: 'agents spawned', message: 'Spawned 3 sub-agents for content multi...', timestamp: new Date(Date.now() - 2 * 60000), color: '#6366f1' },
  { id: '3', agentId: 'gemini', agentName: 'Gemini', type: 'test passed', message: 'QA passed: cross-posting engine v2', timestamp: new Date(Date.now() - 3 * 60000), color: '#ec4899' },
  { id: '4', agentId: 'claude', agentName: 'Claude', type: 'task completed', message: 'PR #142 merged — voice endpoint depl...', timestamp: new Date(Date.now() - 4 * 60000), color: '#f97316' },
  { id: '5', agentId: 'codex', agentName: 'Codex', type: 'brief sent', message: 'Morning brief sent to Alex', timestamp: new Date(Date.now() - 5 * 60000), color: '#6366f1' },
  { id: '6', agentId: 'quill', agentName: 'Quill', type: 'script written', message: 'Blog post draft: "Why Every Founder Ne..."', timestamp: new Date(Date.now() - 7 * 60000), color: '#eab308' },
  { id: '7', agentId: 'pixel', agentName: 'Pixel', type: 'thumbnail generated', message: 'Social cards rendered for 3 platforms', timestamp: new Date(Date.now() - 8 * 60000), color: '#f43f5e' },
  { id: '8', agentId: 'echo', agentName: 'Echo', type: 'content published', message: 'Newsletter dispatched to 2.4k subscribe...', timestamp: new Date(Date.now() - 10 * 60000), color: '#06b6d4' },
];

export const scheduledTasks: ScheduledTask[] = [
  { id: '1', name: 'Reaction Poller', time: 'Recurring', agentId: 'scout', color: '#374151', recurring: true },
  { id: '2', name: 'Trend Radar', time: '12:00 PM', agentId: 'scout', color: '#dc2626', recurring: true },
  { id: '3', name: 'Morning Kickoff', time: '6:55 AM', agentId: 'codex', color: '#374151', recurring: true },
  { id: '4', name: 'YouTube OpenClaw...', time: '7:00 AM', agentId: 'scout', color: '#2563eb', recurring: true },
  { id: '5', name: 'Scout Morning Res...', time: '7:30 AM', agentId: 'scout', color: '#16a34a', recurring: true },
  { id: '6', name: 'Morning Brief', time: '8:00 AM', agentId: 'codex', color: '#ea580c', recurring: true },
  { id: '7', name: 'Trend Radar Daily D...', time: '8:00 AM', agentId: 'scout', color: '#374151', recurring: true },
  { id: '8', name: 'Quill Script Writer', time: '8:30 AM', agentId: 'quill', color: '#7c3aed', recurring: true },
  { id: '9', name: 'Daily Digest', time: '9:00 AM', agentId: 'codex', color: '#0d9488', recurring: true },
  { id: '10', name: 'Evening Wrap Up', time: '9:00 PM', agentId: 'codex', color: '#374151', recurring: true },
];

export const alwaysRunning: AlwaysRunningProcess[] = [
  { name: 'Playbook Scanner', frequency: '4x daily' },
  { name: 'Opportunity Scanner', frequency: '2x daily' },
  { name: 'Competitor Scanner', frequency: '2x daily' },
];

export const daysOfWeek = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
